# merge

In [1]:
import pandas as pd

In [2]:
listed_ratio = pd.read_csv('../processed_data/재무비율.csv')
listed = pd.read_csv('../processed_data/재무지표.csv')

In [3]:
listed_ratio

,회사명,거래소코드,회계년도,소속코드,통계청 한국표준산업분류 코드 10차(대분류),산업코드,산업명,상장일,상장폐지일,총자본증가율(IFRS연결),...,금융비용(IFRS연결)(백만원),임차료(IFRS연결)(백만원),세금과공과(IFRS연결)(백만원),감가상각비(IFRS연결)(백만원),종업원1인당 부가가치(IFRS연결)(백만원).1,총자본투자효율(IFRS연결).1,기계투자효율(IFRS연결).1,부가가치율(IFRS연결).1,종업원수(IFRS연결),label
0,(주)다이나믹디자인,145210,2015,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,-4.56,...,3589.40,0.0,0.0,14203.75,NaN,19.72,98.91,29.06,NaN,1
1,(주)다이나믹디자인,145210,2016,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,-12.91,...,0.00,0.0,0.0,0.00,NaN,-3.89,0.00,-5.57,NaN,1
2,(주)다이나믹디자인,145210,2017,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,-17.07,...,3990.88,0.0,0.0,11694.91,NaN,8.59,44.66,12.60,NaN,1
3,(주)대우건설,47040,2012,1,41,64101,종합 건설업,2001-03-23,NaN,4.13,...,94086.89,124047.0,54145.0,51212.00,NaN,13.73,2422.60,16.47,NaN,0
4,(주)대우건설,47040,2013,1,41,64101,종합 건설업,2001-03-23,NaN,2.67,...,86015.38,123239.0,62921.0,59003.00,NaN,4.00,731.03,4.62,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,한솔아이원스(주),114810,2017,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
388,한솔아이원스(주),114810,2018,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
389,한솔아이원스(주),114810,2019,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,0.00,...,3425.26,0.0,0.0,8607.60,NaN,20.66,165.10,32.15,NaN,1
390,한솔아이원스(주),114810,2020,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,-12.56,...,2408.62,0.0,0.0,7715.50,NaN,27.08,192.48,30.81,NaN,1
391,한솔아이원스(주),114810,2021,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,7.72,...,801.50,0.0,0.0,7955.52,NaN,43.96,353.48,48.15,NaN,1

In [4]:
listed

,회사명,거래소코드,회계년도,소속코드,통계청 한국표준산업분류 코드 10차(대분류),산업코드,산업명,상장일,상장폐지일,현금및현금성자산(*)(IFRS연결)(천원),...,외환차손(IFRS연결)(천원).1,외화환산손실(IFRS연결)(천원).1,지분법적용투자주식손상차손(IFRS연결)(천원),기부금(IFRS연결)(천원),투자자산처분손실(IFRS연결)(천원),보상비(IFRS연결)(천원),법인세추납액(IFRS연결)(천원),전기오류수정손실(IFRS연결)(천원),법인세비용(IFRS연결)(천원),label
0,(주)다이나믹디자인,145210,2015,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,10376890.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,184992.0,1
1,(주)다이나믹디자인,145210,2016,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,15192647.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7248212.0,1
2,(주)다이나믹디자인,145210,2017,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,6564156.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-696299.0,1
3,(주)대우건설,47040,2012,1,41,64101,종합 건설업,2001-03-23,NaN,388440274.0,...,38000000.0,23052000.0,0.0,0.0,0.0,0.0,0.0,0.0,54918791.0,0
4,(주)대우건설,47040,2013,1,41,64101,종합 건설업,2001-03-23,NaN,409596263.0,...,34514000.0,23702000.0,0.0,0.0,0.0,0.0,0.0,0.0,-121688653.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,한솔아이원스(주),114810,2017,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
388,한솔아이원스(주),114810,2018,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
389,한솔아이원스(주),114810,2019,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,12310161.0,...,821838.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2093131.0,1
390,한솔아이원스(주),114810,2020,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,9274990.0,...,799836.0,2359896.0,0.0,0.0,0.0,0.0,0.0,0.0,2536049.0,1
391,한솔아이원스(주),114810,2021,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,16490063.0,...,375920.0,152568.0,0.0,0.0,0.0,0.0,0.0,0.0,10788434.0,1

In [5]:
listed.columns

Index(['회사명', '거래소코드', '회계년도', '소속코드', '통계청 한국표준산업분류 코드 10차(대분류)', '산업코드',
       '산업명', '상장일', '상장폐지일', '현금및현금성자산(*)(IFRS연결)(천원)',
       ...
       '외환차손(IFRS연결)(천원).1', '외화환산손실(IFRS연결)(천원).1',
       '지분법적용투자주식손상차손(IFRS연결)(천원)', '기부금(IFRS연결)(천원)', '투자자산처분손실(IFRS연결)(천원)',
       '보상비(IFRS연결)(천원)', '법인세추납액(IFRS연결)(천원)', '전기오류수정손실(IFRS연결)(천원)',
       '법인세비용(IFRS연결)(천원)', 'label'],
      dtype='object', length=194)

In [6]:
listed_ratio.columns

Index(['회사명', '거래소코드', '회계년도', '소속코드', '통계청 한국표준산업분류 코드 10차(대분류)', '산업코드',
       '산업명', '상장일', '상장폐지일', '총자본증가율(IFRS연결)',
       ...
       '금융비용(IFRS연결)(백만원)', '임차료(IFRS연결)(백만원)', '세금과공과(IFRS연결)(백만원)',
       '감가상각비(IFRS연결)(백만원)', '종업원1인당 부가가치(IFRS연결)(백만원).1', '총자본투자효율(IFRS연결).1',
       '기계투자효율(IFRS연결).1', '부가가치율(IFRS연결).1', '종업원수(IFRS연결)', 'label'],
      dtype='object', length=157)

In [7]:
pd.merge(listed_ratio, listed, on=['회사명', 
                                   '거래소코드', 
                                   '회계년도', 
                                   '소속코드', 
                                   '통계청 한국표준산업분류 코드 10차(대분류)', 
                                   '산업코드', 
                                   '산업명', 
                                   '상장일', 
                                   '상장폐지일', 
                                   'label'])

,회사명,거래소코드,회계년도,소속코드,통계청 한국표준산업분류 코드 10차(대분류),산업코드,산업명,상장일,상장폐지일,총자본증가율(IFRS연결),...,재고자산감모손실(IFRS연결)(천원),외환차손(IFRS연결)(천원).1,외화환산손실(IFRS연결)(천원).1,지분법적용투자주식손상차손(IFRS연결)(천원),기부금(IFRS연결)(천원),투자자산처분손실(IFRS연결)(천원),보상비(IFRS연결)(천원),법인세추납액(IFRS연결)(천원),전기오류수정손실(IFRS연결)(천원),법인세비용(IFRS연결)(천원)
0,(주)다이나믹디자인,145210,2015,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,-4.56,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,184992.0
1,(주)다이나믹디자인,145210,2016,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,-12.91,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7248212.0
2,(주)다이나믹디자인,145210,2017,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,-17.07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-696299.0
3,(주)대우건설,47040,2012,1,41,64101,종합 건설업,2001-03-23,NaN,4.13,...,0.0,38000000.0,23052000.0,0.0,0.0,0.0,0.0,0.0,0.0,54918791.0
4,(주)대우건설,47040,2013,1,41,64101,종합 건설업,2001-03-23,NaN,2.67,...,0.0,34514000.0,23702000.0,0.0,0.0,0.0,0.0,0.0,0.0,-121688653.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,한솔아이원스(주),114810,2017,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
388,한솔아이원스(주),114810,2018,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
389,한솔아이원스(주),114810,2019,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,0.00,...,0.0,821838.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2093131.0
390,한솔아이원스(주),114810,2020,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,-12.56,...,0.0,799836.0,2359896.0,0.0,0.0,0.0,0.0,0.0,0.0,2536049.0
391,한솔아이원스(주),114810,2021,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,7.72,...,0.0,375920.0,152568.0,0.0,0.0,0.0,0.0,0.0,0.0,10788434.0

In [8]:
merge = pd.merge(listed_ratio, listed, on=['회사명'
                                           , '거래소코드'
                                           , '회계년도'
                                           , '소속코드'
                                           , '통계청 한국표준산업분류 코드 10차(대분류)', 
                                           '산업코드', 
                                           '산업명', 
                                           '상장일', 
                                           '상장폐지일', 
                                           'label'])

In [9]:
# a = listed_ratio[['회사명', 'label']]
# b = listed[['회사명', 'label']]
# c = pd.merge(a, b, on='회사명')

In [10]:
# c.to_csv('./check.csv', index=False, encoding='UTF-8-sig')

In [11]:
merge.to_csv('../processed_data/재무비율_재무지표.csv', index=False, encoding='UTF-8-sig')