In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_index = pd.read_csv("../data/processed_data/재무지표_150개이상제거완.csv", index_col=0)
# df_index.head()

In [3]:
df_ratio = pd.read_csv("../data/processed_data/재무비율_처리완.csv")
# df_ratio.head()

In [4]:
print(len(df_index.columns))
print(len(df_ratio.columns))
print('-------------------')
print(len(df_index))
print(len(df_ratio))

63
151
-------------------
389
389

In [5]:
df_index.columns[df_index.isnull().sum() > 0]

Index(['상장폐지일', '상각후원가측정 유가증권(IFRS)', '배출권자산(IFRS)', '당기법인세부채(미지급법인세)(IFRS)',
       '이자수익(IFRS)'],
      dtype='object')

In [6]:
df_ratio.columns[df_ratio.isnull().sum() > 0]

Index(['상장폐지일'], dtype='object')

In [7]:
df_index[df_index.columns[9:]] = df_index[df_index.columns[9:]].fillna(0)

df_index.columns[df_index.isnull().sum() > 0]

Index(['상장폐지일'], dtype='object')

In [8]:
df_merged = pd.merge(df_index, df_ratio,
                     on = ['회사명', '거래소코드', '회계년도', '소속코드', '통계청 한국표준산업분류 코드 10차(대분류)', '산업코드', '산업명', '상장일', '상장폐지일'],
                     how='inner', suffixes=('_index', '_ratio'))
df_merged.drop(columns = 'label_index', inplace = True)
df_merged.rename(columns = {'label_ratio' : 'label'}, inplace = True)

In [9]:
df_merged

,회사명,거래소코드,회계년도,소속코드,통계청 한국표준산업분류 코드 10차(대분류),산업코드,산업명,상장일,상장폐지일,현금및현금성자산(IFRS),...,자본분배율(IFRS),이윤분배율(IFRS),법인세비용차감전(계속사업)손익(IFRS)(백만원),인건비(IFRS)(백만원),금융비용(IFRS)(백만원),임차료(IFRS)(백만원),세금과공과(IFRS)(백만원),감가상각비(IFRS)(백만원),종업원수(IFRS),label
0,(주)다이나믹디자인,145210,2015,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,10376890.0,...,29.18,2.06,1548.77,46876.84,3589.40,0.0,0.0,14203.75,150.0,1
1,(주)다이나믹디자인,145210,2016,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,15192647.0,...,0.00,0.00,-11379.61,0.00,0.00,0.0,0.0,0.00,134.0,1
2,(주)다이나믹디자인,145210,2017,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,6564156.0,...,-90.09,-161.93,-34429.26,39598.55,3990.88,0.0,0.0,11694.91,526.0,1
3,(주)대우건설,47040,2012,1,41,64101,종합 건설업,2001-03-23,NaN,388440274.0,...,40.72,12.78,227947.72,802635.00,94086.89,124047.0,54145.0,51212.00,5192.0,0
4,(주)대우건설,47040,2013,1,41,64101,종합 건설업,2001-03-23,NaN,409596263.0,...,-125.45,-177.13,-839724.66,913926.00,86015.38,123239.0,62921.0,59003.00,6382.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,한솔아이원스(주),114810,2017,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,9892897.0,...,40.36,-1.99,-79.97,19022.41,5048.10,0.0,0.0,7923.59,519.0,1
385,한솔아이원스(주),114810,2018,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,5510953.0,...,32.63,2.39,-678.20,24417.40,3831.05,0.0,0.0,8695.36,608.0,1
386,한솔아이원스(주),114810,2019,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,12310161.0,...,22.96,-2.27,-2987.27,30291.89,3425.26,0.0,0.0,8607.60,538.0,1
387,한솔아이원스(주),114810,2020,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,9274990.0,...,36.33,8.28,6268.86,28696.72,2408.62,0.0,0.0,7715.50,539.0,1
388,한솔아이원스(주),114810,2021,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,16490063.0,...,59.81,35.03,38392.03,31674.81,801.50,0.0,0.0,7955.52,551.0,1

In [ ]:
# df_merged.to_csv('../data/processed_data/재무비율_재무지표_concat_fix.csv', index=False, encoding='UTF-8-sig')