In [11]:
import pandas as pd

In [12]:
kospi = pd.read_excel('../data/raw_data/코스피_개별_논문.xlsx')
kosdaq = pd.read_excel('../data/raw_data/코스닥_개별_논문.xlsx')

In [13]:
print('kospi: ', kospi.shape)
print('kosdaq: ', kosdaq.shape)

kospi:  (8997, 193)
kosdaq:  (18731, 193)

In [14]:
print('kospi: ', kospi.drop_duplicates('거래소코드').shape)
print('kosdaq: ', kosdaq.drop_duplicates('거래소코드').shape)

kospi:  (820, 193)
kosdaq:  (1908, 193)

In [15]:
listed = pd.concat([kospi, kosdaq], ignore_index=True)

In [16]:
listed[listed['거래소코드'] == 68270]

,회사명,거래소코드,회계년도,소속코드,통계청 한국표준산업분류 코드 10차(대분류),산업코드,산업명,상장일,상장폐지일,현금및현금성자산(*)(IFRS)(천원),...,재고자산감모손실(IFRS)(천원),외환차손(IFRS)(천원).1,외화환산손실(IFRS)(천원).1,지분법적용투자주식손상차손(IFRS)(천원),기부금(IFRS)(천원),투자자산처분손실(IFRS)(천원),보상비(IFRS)(천원),법인세추납액(IFRS)(천원),전기오류수정손실(IFRS)(천원),법인세비용(IFRS)(천원)
1444,(주)셀트리온,68270,2012/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,5.097772e+07,...,0.0,98995.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13253679.0
1445,(주)셀트리온,68270,2013/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,7.952414e+07,...,0.0,511338.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13012009.0
1446,(주)셀트리온,68270,2014/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,1.051597e+08,...,0.0,210098.0,10349710.0,0.0,0.0,0.0,0.0,0.0,0.0,34141101.0
1447,(주)셀트리온,68270,2015/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,1.396181e+08,...,0.0,2456329.0,4374450.0,0.0,0.0,0.0,0.0,0.0,0.0,21172775.0
1448,(주)셀트리온,68270,2016/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,2.576048e+08,...,0.0,1490126.0,2278410.0,0.0,0.0,0.0,0.0,0.0,0.0,48209135.0
1449,(주)셀트리온,68270,2017/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,4.135019e+08,...,0.0,2557869.0,10826845.0,0.0,0.0,0.0,0.0,0.0,0.0,106443550.0
1450,(주)셀트리온,68270,2018/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,3.995584e+08,...,0.0,3014260.0,4652.0,0.0,0.0,0.0,0.0,0.0,0.0,57913668.0
1451,(주)셀트리온,68270,2019/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,5.260928e+08,...,0.0,1759508.0,1582361.0,0.0,0.0,0.0,0.0,0.0,0.0,79351820.0
1452,(주)셀트리온,68270,2020/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,6.152167e+08,...,0.0,17232045.0,12797752.0,0.0,0.0,0.0,0.0,0.0,0.0,135618816.0
1453,(주)셀트리온,68270,2021/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,1.078949e+09,...,0.0,4193102.0,19356.0,0.0,0.0,0.0,0.0,0.0,0.0,147857696.0
1454,(주)셀트리온,68270,2022/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,5.013595e+08,...,0.0,5240761.0,698547.0,0.0,0.0,0.0,0.0,0.0,0.0,95006836.0
1455,(주)셀트리온,68270,2023/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,3.726613e+08,...,0.0,7365967.0,2793670.0,0.0,0.0,0.0,0.0,0.0,0.0,119205291.0
13137,(주)셀트리온,68270,2012/12,4,21,32101,의료용 물질 및 의약품 제조업,2005/07/15,2018/02/09,5.097772e+07,...,0.0,98995.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13253679.0
13138,(주)셀트리온,68270,2013/12,4,21,32101,의료용 물질 및 의약품 제조업,2005/07/15,2018/02/09,7.952414e+07,...,0.0,511338.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13012009.0
13139,(주)셀트리온,68270,2014/12,4,21,32101,의료용 물질 및 의약품 제조업,2005/07/15,2018/02/09,1.051597e+08,...,0.0,210098.0,10349710.0,0.0,0.0,0.0,0.0,0.0,0.0,34141101.0
13140,(주)셀트리온,68270,2015/12,4,21,32101,의료용 물질 및 의약품 제조업,2005/07/15,2018/02/09,1.396181e+08,...,0.0,2456329.0,4374450.0,0.0,0.0,0.0,0.0,0.0,0.0,21172775.0
13141,(주)셀트리온,68270,2016/12,4,21,32101,의료용 물질 및 의약품 제조업,2005/07/15,2018/02/09,2.576048e+08,...,0.0,1490126.0,2278410.0,0.0,0.0,0.0,0.0,0.0,0.0,48209135.0

In [17]:
listed.shape

(27728, 193)

In [18]:
listed.drop_duplicates('거래소코드').shape

(2712, 193)

# 결산월이 12월인 기업만

In [19]:
listed['회계년도'] = pd.to_datetime(listed['회계년도'], format='%Y/%m')
listed = listed[listed['회계년도'].dt.month == 12]

In [20]:
listed.shape

(27549, 193)

In [21]:
listed.drop_duplicates('거래소코드').shape

(2711, 193)

# 특수 목적 회사 drop
- 1차 통계청 한국표준산업분류(KSIC) 기준으로 제거
    - K. 금융및보험업(64~66)
        - 64. 금융업
        - 65. 보험및연금업
        - 66. 금융및보험관련서비스업
- 2차 키워드 제거
    - 인베스트|투자|금융|보험|캐피탈|특수목적|프로젝트|문화산업

In [22]:
listed = listed[~listed['통계청 한국표준산업분류 코드 10차(대분류)'].isin([64, 65, 66])]
listed = listed[~listed['회사명'].str.contains('인베스트|투자|금융|보험|캐피탈|특수목적|프로젝트|문화산업')]

In [23]:
listed.shape

(27383, 193)

In [24]:
listed.drop_duplicates('거래소코드').shape

(2696, 193)

# 이전 상장에 따른 중복 데이터 제거

In [25]:
# Step 1: 소속코드가 4와 1을 모두 가지는 거래소코드 찾기
# 거래소코드별로 그룹화하여 소속코드를 집합으로 만든 후, 조건을 만족하는 거래소코드를 필터링합니다.
grouped = listed.groupby('거래소코드')['소속코드'].apply(set)
target_codes = grouped[grouped.apply(lambda x: {1, 4}.issubset(x))].index
target_codes

Index([  3670,  22100,  26960,  30190,  34230,  35510,  35720,  36420,  66970,
        68270,  90460,  97520, 100090, 108320, 178920, 192080],
      dtype='int64', name='거래소코드')

In [26]:
# Step 2: 소속코드가 4이고 상장폐지일이 존재하는 행 제거
listed = listed[~((listed['거래소코드'].isin(target_codes)) & (listed['소속코드'] == 4) & (~listed['상장폐지일'].isna()))]

In [27]:
listed.shape

(27255, 193)

In [28]:
listed.drop_duplicates('거래소코드').shape

(2696, 193)

# 상장 이전 데이터 제거

In [29]:
listed[['회계년도', '상장일']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 27255 entries, 0 to 27727
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   회계년도    27255 non-null  datetime64[ns]
 1   상장일     27255 non-null  object
dtypes: datetime64[ns](1), object(1)
memory usage: 638.8+ KB

In [30]:
listed['상장일'] = pd.to_datetime(listed['상장일'], format='%Y/%m/%d')

In [31]:
# 회계년도가 상장년도 이전(미만)인 데이터 제거
listed[listed['회계년도'].dt.year < listed['상장일'].dt.year][['회사명', '거래소코드', '회계년도', '상장일']]

             회사명   거래소코드       회계년도        상장일
140      (주)경보제약  214390 2012-12-01 2015-06-29
141      (주)경보제약  214390 2013-12-01 2015-06-29
142      (주)경보제약  214390 2014-12-01 2015-06-29
224    (주)금호에이치티  214330 2012-12-01 2015-11-11
225    (주)금호에이치티  214330 2013-12-01 2015-11-11
...          ...     ...        ...        ...
27670  휴림네트웍스(주)  192410 2012-12-01 2014-08-14
27671  휴림네트웍스(주)  192410 2013-12-01 2014-08-14
27704      휴젤(주)  145020 2012-12-01 2015-12-24
27705      휴젤(주)  145020 2013-12-01 2015-12-24
27706      휴젤(주)  145020 2014-12-01 2015-12-24

[3954 rows x 4 columns]

In [32]:
# 회계년도가 상장년도 이전(미만)인 데이터 제거
listed = listed[listed['회계년도'].dt.year >= listed['상장일'].dt.year]

In [33]:
listed.shape

(23301, 193)

In [34]:
listed.drop_duplicates('거래소코드').shape

(2637, 193)

# merge

### 회계 감리 지적 기업 csv 불러오기

In [35]:
fraud = pd.read_csv('../data/raw_data/회계 감리 지적 기업.csv')

In [36]:
print('fraud 로우 수: ', fraud.shape)
print('fraud 기업 수: ', fraud.drop_duplicates('거래소코드').shape)

fraud 로우 수:  (498, 5)
fraud 기업 수:  (138, 5)

In [37]:
# 중복 행 제거 후 인덱스 리셋
fraud = fraud.drop_duplicates().reset_index(drop=True)

In [38]:
print('fraud 로우 수: ', fraud.shape)
print('fraud 기업 수: ', fraud.drop_duplicates('거래소코드').shape)

fraud 로우 수:  (445, 5)
fraud 기업 수:  (138, 5)

### 기준이 되는 데이터 타입 맞추기

In [39]:
listed[['거래소코드', '회계년도']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 23301 entries, 0 to 27727
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   거래소코드   23301 non-null  int64
 1   회계년도    23301 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1)
memory usage: 546.1 KB

In [40]:
fraud[['거래소코드', '회계년도']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 445 entries, 0 to 444
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   거래소코드   445 non-null    int64
 1   회계년도    445 non-null    int64
dtypes: int64(2)
memory usage: 7.1 KB

In [41]:
listed['회계년도'] = listed['회계년도'].dt.year

### pd.merge(listed, fraud, on=['거래소코드', '회계년도'])

In [42]:
listed = pd.merge(listed, fraud, on=['거래소코드', '회계년도'])

In [43]:
listed.shape

(403, 196)

In [44]:
listed.drop_duplicates('거래소코드').shape

(132, 196)

In [45]:
print(listed[listed['기업유형'] == '코스피'].shape)
print(listed[listed['기업유형'] == '코스닥'].shape)

(128, 196)
(275, 196)

In [46]:
print(listed[listed['기업유형'] == '코스피'].drop_duplicates('거래소코드').shape)
print(listed[listed['기업유형'] == '코스닥'].drop_duplicates('거래소코드').shape)

(40, 196)
(92, 196)

# 정리

In [47]:
listed.columns

Index(['회사명', '거래소코드', '회계년도', '소속코드', '통계청 한국표준산업분류 코드 10차(대분류)', '산업코드',
       '산업명', '상장일', '상장폐지일', '현금및현금성자산(*)(IFRS)(천원)',
       ...
       '지분법적용투자주식손상차손(IFRS)(천원)', '기부금(IFRS)(천원)', '투자자산처분손실(IFRS)(천원)',
       '보상비(IFRS)(천원)', '법인세추납액(IFRS)(천원)', '전기오류수정손실(IFRS)(천원)',
       '법인세비용(IFRS)(천원)', '기업명', '기업유형', '이익 과대계상 (비용 과소계상)'],
      dtype='object', length=196)

In [48]:
listed = listed.drop(columns = ['기업명', '기업유형'])
listed.columns

Index(['회사명', '거래소코드', '회계년도', '소속코드', '통계청 한국표준산업분류 코드 10차(대분류)', '산업코드',
       '산업명', '상장일', '상장폐지일', '현금및현금성자산(*)(IFRS)(천원)',
       ...
       '외환차손(IFRS)(천원).1', '외화환산손실(IFRS)(천원).1', '지분법적용투자주식손상차손(IFRS)(천원)',
       '기부금(IFRS)(천원)', '투자자산처분손실(IFRS)(천원)', '보상비(IFRS)(천원)',
       '법인세추납액(IFRS)(천원)', '전기오류수정손실(IFRS)(천원)', '법인세비용(IFRS)(천원)',
       '이익 과대계상 (비용 과소계상)'],
      dtype='object', length=194)

In [49]:
listed = listed.rename(columns={'회사명_x': '회사명', '이익 과대계상 (비용 과소계상)': 'label'})
listed.columns

Index(['회사명', '거래소코드', '회계년도', '소속코드', '통계청 한국표준산업분류 코드 10차(대분류)', '산업코드',
       '산업명', '상장일', '상장폐지일', '현금및현금성자산(*)(IFRS)(천원)',
       ...
       '외환차손(IFRS)(천원).1', '외화환산손실(IFRS)(천원).1', '지분법적용투자주식손상차손(IFRS)(천원)',
       '기부금(IFRS)(천원)', '투자자산처분손실(IFRS)(천원)', '보상비(IFRS)(천원)',
       '법인세추납액(IFRS)(천원)', '전기오류수정손실(IFRS)(천원)', '법인세비용(IFRS)(천원)', 'label'],
      dtype='object', length=194)

In [50]:
listed_describe = listed.iloc[:, 8:-1].describe()
listed_describe

,현금및현금성자산(*)(IFRS)(천원),유동금융자산(*)(IFRS)(천원),매출채권 및 기타유동채권(*)(IFRS)(천원),이연법인세자산(IFRS)(천원),상각후원가측정 유가증권(IFRS)(천원),매출채권(IFRS)(천원),미수금(IFRS)(천원),단기대여금(IFRS)(천원),선급금(IFRS)(천원),기타유동자산(*)(IFRS)(천원),...,재고자산감모손실(IFRS)(천원),외환차손(IFRS)(천원).1,외화환산손실(IFRS)(천원).1,지분법적용투자주식손상차손(IFRS)(천원),기부금(IFRS)(천원),투자자산처분손실(IFRS)(천원),보상비(IFRS)(천원),법인세추납액(IFRS)(천원),전기오류수정손실(IFRS)(천원),법인세비용(IFRS)(천원)
count,4.030000e+02,4.030000e+02,4.030000e+02,4.030000e+02,140.000000,4.030000e+02,4.030000e+02,4.030000e+02,4.030000e+02,4.030000e+02,...,403.0,4.030000e+02,4.030000e+02,403.0,403.0,403.0,403.000000,403.0,403.0,4.030000e+02
mean,4.797796e+07,4.425392e+07,2.066668e+08,1.512609e+07,322.500000,7.364242e+07,2.728208e+07,1.249887e+07,2.799558e+07,4.901949e+07,...,0.0,2.685585e+06,1.053642e+06,0.0,0.0,0.0,7219.459057,0.0,0.0,4.005985e+06
std,1.535461e+08,1.829964e+08,7.491920e+08,8.975350e+07,3273.901183,2.721624e+08,1.225743e+08,4.987875e+07,1.327937e+08,2.041166e+08,...,0.0,1.293018e+07,6.027438e+06,0.0,0.0,0.0,58042.768982,0.0,0.0,6.904090e+07
min,1.950000e+02,0.000000e+00,3.561000e+03,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,-1.034523e+09
25%,1.429482e+06,5.982025e+05,6.769954e+06,0.000000e+00,0.000000,5.628839e+06,3.860260e+05,1.131000e+03,1.525215e+05,3.567070e+05,...,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000e+00
50%,5.510953e+06,4.009577e+06,1.869601e+07,0.000000e+00,0.000000,1.387370e+07,1.184954e+06,8.815000e+05,1.248108e+06,1.327122e+06,...,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,3.486900e+04
75%,1.769381e+07,1.382930e+07,4.388084e+07,2.142647e+06,0.000000,3.162059e+07,5.224702e+06,6.110941e+06,5.102156e+06,4.791024e+06,...,0.0,2.407665e+05,5.057250e+04,0.0,0.0,0.0,0.000000,0.0,0.0,2.001595e+06
max,1.374706e+09,2.072716e+09,5.225435e+09,1.419954e+09,38150.000000,3.587764e+09,1.099663e+09,7.399209e+08,1.745086e+09,1.893955e+09,...,0.0,1.748380e+08,7.385200e+07,0.0,0.0,0.0,745141.000000,0.0,0.0,3.261462e+08

### 중복된 내용 drop
- 회계 감리 지적 기업을 정리하는 과정에서 팀원 간 겹치는 보고서가 있었음.

In [51]:
listed[listed['회사명'] == '(주)제이테크놀로지']

,회사명,거래소코드,회계년도,소속코드,통계청 한국표준산업분류 코드 10차(대분류),산업코드,산업명,상장일,상장폐지일,현금및현금성자산(*)(IFRS)(천원),...,외환차손(IFRS)(천원).1,외화환산손실(IFRS)(천원).1,지분법적용투자주식손상차손(IFRS)(천원),기부금(IFRS)(천원),투자자산처분손실(IFRS)(천원),보상비(IFRS)(천원),법인세추납액(IFRS)(천원),전기오류수정손실(IFRS)(천원),법인세비용(IFRS)(천원),label
278,(주)제이테크놀로지,35480,2012,4,91,189102,스포츠 및 오락관련 서비스업,1999-11-18,2019/12/12,2557730.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
279,(주)제이테크놀로지,35480,2012,4,91,189102,스포츠 및 오락관련 서비스업,1999-11-18,2019/12/12,2557730.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
280,(주)제이테크놀로지,35480,2013,4,91,189102,스포츠 및 오락관련 서비스업,1999-11-18,2019/12/12,481364.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
281,(주)제이테크놀로지,35480,2013,4,91,189102,스포츠 및 오락관련 서비스업,1999-11-18,2019/12/12,481364.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
282,(주)제이테크놀로지,35480,2014,4,91,189102,스포츠 및 오락관련 서비스업,1999-11-18,2019/12/12,7383098.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
283,(주)제이테크놀로지,35480,2014,4,91,189102,스포츠 및 오락관련 서비스업,1999-11-18,2019/12/12,7383098.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
284,(주)제이테크놀로지,35480,2015,4,91,189102,스포츠 및 오락관련 서비스업,1999-11-18,2019/12/12,10227694.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2788963.0,1
285,(주)제이테크놀로지,35480,2015,4,91,189102,스포츠 및 오락관련 서비스업,1999-11-18,2019/12/12,10227694.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2788963.0,1
286,(주)제이테크놀로지,35480,2016,4,91,189102,스포츠 및 오락관련 서비스업,1999-11-18,2019/12/12,8028212.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,867838.0,1
287,(주)제이테크놀로지,35480,2016,4,91,189102,스포츠 및 오락관련 서비스업,1999-11-18,2019/12/12,8028212.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,867838.0,1
288,(주)제이테크놀로지,35480,2017,4,91,189102,스포츠 및 오락관련 서비스업,1999-11-18,2019/12/12,306672.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-319128.0,1

In [52]:
listed = listed.drop_duplicates()
listed

,회사명,거래소코드,회계년도,소속코드,통계청 한국표준산업분류 코드 10차(대분류),산업코드,산업명,상장일,상장폐지일,현금및현금성자산(*)(IFRS)(천원),...,외환차손(IFRS)(천원).1,외화환산손실(IFRS)(천원).1,지분법적용투자주식손상차손(IFRS)(천원),기부금(IFRS)(천원),투자자산처분손실(IFRS)(천원),보상비(IFRS)(천원),법인세추납액(IFRS)(천원),전기오류수정손실(IFRS)(천원),법인세비용(IFRS)(천원),label
0,(주)다이나믹디자인,145210,2015,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,5547269.0,...,2136822.0,2881977.0,0.0,0.0,0.0,0.0,0.0,0.0,1032733.0,1
1,(주)다이나믹디자인,145210,2016,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,7869589.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9539579.0,1
2,(주)다이나믹디자인,145210,2017,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,1514457.0,...,2365382.0,2147683.0,0.0,0.0,0.0,0.0,0.0,0.0,-4431729.0,1
3,(주)대우건설,47040,2012,1,41,64101,종합 건설업,2001-03-23,NaN,323571800.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,56151157.0,0
4,(주)대우건설,47040,2013,1,41,64101,종합 건설업,2001-03-23,NaN,324046180.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-127568854.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,한솔아이원스(주),114810,2017,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,9892897.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,553201.0,1
399,한솔아이원스(주),114810,2018,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,5510953.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1544374.0,1
400,한솔아이원스(주),114810,2019,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,12307845.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2093131.0,1
401,한솔아이원스(주),114810,2020,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,9272814.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2536049.0,1
402,한솔아이원스(주),114810,2021,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,16487692.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10788434.0,1

In [53]:
listed_describe = listed.iloc[:, 8:-1].describe()
listed_describe

,현금및현금성자산(*)(IFRS)(천원),유동금융자산(*)(IFRS)(천원),매출채권 및 기타유동채권(*)(IFRS)(천원),이연법인세자산(IFRS)(천원),상각후원가측정 유가증권(IFRS)(천원),매출채권(IFRS)(천원),미수금(IFRS)(천원),단기대여금(IFRS)(천원),선급금(IFRS)(천원),기타유동자산(*)(IFRS)(천원),...,재고자산감모손실(IFRS)(천원),외환차손(IFRS)(천원).1,외화환산손실(IFRS)(천원).1,지분법적용투자주식손상차손(IFRS)(천원),기부금(IFRS)(천원),투자자산처분손실(IFRS)(천원),보상비(IFRS)(천원),법인세추납액(IFRS)(천원),전기오류수정손실(IFRS)(천원),법인세비용(IFRS)(천원)
count,3.920000e+02,3.920000e+02,3.920000e+02,3.920000e+02,139.000000,3.920000e+02,3.920000e+02,3.920000e+02,3.920000e+02,3.920000e+02,...,392.0,3.920000e+02,3.920000e+02,392.0,392.0,392.0,392.000000,392.0,392.0,3.920000e+02
mean,4.919750e+07,4.519049e+07,2.122943e+08,1.554724e+07,324.820144,7.552398e+07,2.801092e+07,1.266691e+07,2.868871e+07,5.032264e+07,...,0.0,2.759097e+06,1.081447e+06,0.0,0.0,0.0,7422.045918,0.0,0.0,4.076497e+06
std,1.555140e+08,1.854618e+08,7.588912e+08,9.097144e+07,3285.626218,2.757279e+08,1.242079e+08,5.055975e+07,1.345825e+08,2.068169e+08,...,0.0,1.310321e+07,6.109228e+06,0.0,0.0,0.0,58840.756178,0.0,0.0,7.000264e+07
min,1.950000e+02,0.000000e+00,3.561000e+03,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,-1.034523e+09
25%,1.425482e+06,5.632170e+05,7.005533e+06,0.000000e+00,0.000000,5.798289e+06,3.777840e+05,3.000000e+02,1.473732e+05,3.458660e+05,...,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,-2.200000e+01
50%,5.543538e+06,3.885828e+06,1.945342e+07,8.066500e+04,0.000000,1.446600e+07,1.198418e+06,8.762510e+05,1.183553e+06,1.296975e+06,...,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,4.838050e+04
75%,1.880755e+07,1.375724e+07,4.456054e+07,2.203674e+06,0.000000,3.189767e+07,5.481572e+06,5.888236e+06,5.124709e+06,4.840473e+06,...,0.0,2.608332e+05,5.457700e+04,0.0,0.0,0.0,0.000000,0.0,0.0,1.994783e+06
max,1.374706e+09,2.072716e+09,5.225435e+09,1.419954e+09,38150.000000,3.587764e+09,1.099663e+09,7.399209e+08,1.745086e+09,1.893955e+09,...,0.0,1.748380e+08,7.385200e+07,0.0,0.0,0.0,745141.000000,0.0,0.0,3.261462e+08

# csv로 저장

In [54]:
# listed.to_csv('../data/processed_data/개별재무지표.csv', index=False, encoding='UTF-8-sig')

In [55]:
# listed_describe.to_csv('../data/processed_data/개별_재무지표_기초통계량.csv', index=False, encoding='UTF-8-sig')