In [1]:
import pandas as pd

In [2]:
kospi = pd.read_excel('../data/raw_data/코스피_논문.xlsx')
kosdaq = pd.read_excel('../data/raw_data/코스닥_논문.xlsx')

In [3]:
print('kospi: ', kospi.shape)
print('kosdaq: ', kosdaq.shape)

kospi:  (8997, 193)
kosdaq:  (18698, 193)

In [4]:
print('kospi: ', kospi.drop_duplicates('거래소코드').shape)
print('kosdaq: ', kosdaq.drop_duplicates('거래소코드').shape)

kospi:  (820, 193)
kosdaq:  (1903, 193)

In [5]:
listed = pd.concat([kospi, kosdaq], ignore_index=True)

In [6]:
listed[listed['거래소코드'] == 68270]

,회사명,거래소코드,회계년도,소속코드,통계청 한국표준산업분류 코드 10차(대분류),산업코드,산업명,상장일,상장폐지일,현금및현금성자산(*)(IFRS연결)(천원),...,재고자산감모손실(IFRS연결)(천원),외환차손(IFRS연결)(천원).1,외화환산손실(IFRS연결)(천원).1,지분법적용투자주식손상차손(IFRS연결)(천원),기부금(IFRS연결)(천원),투자자산처분손실(IFRS연결)(천원),보상비(IFRS연결)(천원),법인세추납액(IFRS연결)(천원),전기오류수정손실(IFRS연결)(천원),법인세비용(IFRS연결)(천원)
1444,(주)셀트리온,68270,2012/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,5.315923e+07,...,0.0,537533.0,261983.0,0.0,0.0,0.0,0.0,0.0,0.0,13135596.0
1445,(주)셀트리온,68270,2013/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,8.075387e+07,...,0.0,1700561.0,730.0,0.0,0.0,0.0,0.0,0.0,0.0,13209769.0
1446,(주)셀트리온,68270,2014/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,1.087524e+08,...,0.0,2541254.0,17669.0,0.0,0.0,0.0,0.0,0.0,0.0,31629576.0
1447,(주)셀트리온,68270,2015/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,1.499261e+08,...,0.0,3096701.0,21271.0,0.0,0.0,0.0,0.0,0.0,0.0,4829113.0
1448,(주)셀트리온,68270,2016/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,2.684081e+08,...,0.0,2888315.0,215635.0,0.0,0.0,0.0,0.0,0.0,0.0,48014632.0
1449,(주)셀트리온,68270,2017/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,4.192057e+08,...,0.0,2528208.0,151133.0,0.0,0.0,0.0,0.0,0.0,0.0,105346399.0
1450,(주)셀트리온,68270,2018/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,4.105476e+08,...,0.0,7376642.0,417839.0,0.0,0.0,0.0,0.0,0.0,0.0,64162718.0
1451,(주)셀트리온,68270,2019/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,5.461376e+08,...,0.0,3354249.0,2168770.0,0.0,0.0,0.0,0.0,0.0,0.0,80588584.0
1452,(주)셀트리온,68270,2020/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,6.842939e+08,...,0.0,7322427.0,4431102.0,0.0,0.0,0.0,0.0,0.0,0.0,131449106.0
1453,(주)셀트리온,68270,2021/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,1.188326e+09,...,0.0,7751877.0,1913004.0,0.0,0.0,0.0,0.0,0.0,0.0,155530434.0
1454,(주)셀트리온,68270,2022/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,5.511867e+08,...,0.0,23704271.0,1644512.0,0.0,0.0,0.0,0.0,0.0,0.0,94826673.0
1455,(주)셀트리온,68270,2023/12,1,21,32101,의료용 물질 및 의약품 제조업,2018/02/09,NaN,5.646117e+08,...,0.0,16415776.0,3347883.0,0.0,0.0,0.0,0.0,0.0,0.0,131389280.0
13127,(주)셀트리온,68270,2012/12,4,21,32101,의료용 물질 및 의약품 제조업,2005/07/15,2018/02/09,5.315923e+07,...,0.0,537533.0,261983.0,0.0,0.0,0.0,0.0,0.0,0.0,13135596.0
13128,(주)셀트리온,68270,2013/12,4,21,32101,의료용 물질 및 의약품 제조업,2005/07/15,2018/02/09,8.075387e+07,...,0.0,1700561.0,730.0,0.0,0.0,0.0,0.0,0.0,0.0,13209769.0
13129,(주)셀트리온,68270,2014/12,4,21,32101,의료용 물질 및 의약품 제조업,2005/07/15,2018/02/09,1.087524e+08,...,0.0,2541254.0,17669.0,0.0,0.0,0.0,0.0,0.0,0.0,31629576.0
13130,(주)셀트리온,68270,2015/12,4,21,32101,의료용 물질 및 의약품 제조업,2005/07/15,2018/02/09,1.499261e+08,...,0.0,3096701.0,21271.0,0.0,0.0,0.0,0.0,0.0,0.0,4829113.0
13131,(주)셀트리온,68270,2016/12,4,21,32101,의료용 물질 및 의약품 제조업,2005/07/15,2018/02/09,2.684081e+08,...,0.0,2888315.0,215635.0,0.0,0.0,0.0,0.0,0.0,0.0,48883293.0

In [7]:
listed.shape

(27695, 193)

In [8]:
listed.drop_duplicates('거래소코드').shape

(2707, 193)

# 결산월이 12월인 기업만

In [9]:
listed['회계년도'] = pd.to_datetime(listed['회계년도'], format='%Y/%m')
listed = listed[listed['회계년도'].dt.month == 12]

In [10]:
listed.shape

(27516, 193)

In [11]:
listed.drop_duplicates('거래소코드').shape

(2706, 193)

# 특수 목적 회사 drop
- 1차 통계청 한국표준산업분류(KSIC) 기준으로 제거
    - K. 금융및보험업(64~66)
        - 64. 금융업
        - 65. 보험및연금업
        - 66. 금융및보험관련서비스업
- 2차 키워드 제거
    - 인베스트|투자|금융|보험|캐피탈|특수목적|프로젝트|문화산업

In [12]:
listed = listed[~listed['통계청 한국표준산업분류 코드 10차(대분류)'].isin([64, 65, 66])]
listed = listed[~listed['회사명'].str.contains('인베스트|투자|금융|보험|캐피탈|특수목적|프로젝트|문화산업')]

In [13]:
listed.shape

(27350, 193)

In [14]:
listed.drop_duplicates('거래소코드').shape

(2691, 193)

# 이전 상장에 따른 중복 데이터 제거

In [15]:
# Step 1: 소속코드가 4와 1을 모두 가지는 거래소코드 찾기
# 거래소코드별로 그룹화하여 소속코드를 집합으로 만든 후, 조건을 만족하는 거래소코드를 필터링합니다.
grouped = listed.groupby('거래소코드')['소속코드'].apply(set)
target_codes = grouped[grouped.apply(lambda x: {1, 4}.issubset(x))].index
target_codes

Index([  3670,  22100,  26960,  30190,  34230,  35510,  35720,  36420,  66970,
        68270,  90460,  97520, 100090, 108320, 178920, 192080],
      dtype='int64', name='거래소코드')

In [16]:
# Step 2: 소속코드가 4이고 상장폐지일이 존재하는 행 제거
listed = listed[~((listed['거래소코드'].isin(target_codes)) & (listed['소속코드'] == 4) & (~listed['상장폐지일'].isna()))]

In [17]:
listed.shape

(27222, 193)

In [18]:
listed.drop_duplicates('거래소코드').shape

(2691, 193)

# 상장 이전 데이터 제거

In [19]:
listed[['회계년도', '상장일']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 27222 entries, 0 to 27694
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   회계년도    27222 non-null  datetime64[ns]
 1   상장일     27222 non-null  object
dtypes: datetime64[ns](1), object(1)
memory usage: 638.0+ KB

In [20]:
listed['상장일'] = pd.to_datetime(listed['상장일'], format='%Y/%m/%d')

In [21]:
# 회계년도가 상장년도 이전(미만)인 데이터 제거
listed[listed['회계년도'].dt.year < listed['상장일'].dt.year][['회사명', '거래소코드', '회계년도', '상장일']]

             회사명   거래소코드       회계년도        상장일
140      (주)경보제약  214390 2012-12-01 2015-06-29
141      (주)경보제약  214390 2013-12-01 2015-06-29
142      (주)경보제약  214390 2014-12-01 2015-06-29
224    (주)금호에이치티  214330 2012-12-01 2015-11-11
225    (주)금호에이치티  214330 2013-12-01 2015-11-11
...          ...     ...        ...        ...
27637  휴림네트웍스(주)  192410 2012-12-01 2014-08-14
27638  휴림네트웍스(주)  192410 2013-12-01 2014-08-14
27671      휴젤(주)  145020 2012-12-01 2015-12-24
27672      휴젤(주)  145020 2013-12-01 2015-12-24
27673      휴젤(주)  145020 2014-12-01 2015-12-24

[3929 rows x 4 columns]

In [22]:
# 회계년도가 상장년도 이전(미만)인 데이터 제거
listed = listed[listed['회계년도'].dt.year >= listed['상장일'].dt.year]

In [23]:
listed.shape

(23293, 193)

In [24]:
listed.drop_duplicates('거래소코드').shape

(2636, 193)

# merge

### 회계 감리 지적 기업 csv 불러오기

In [25]:
fraud = pd.read_csv('../data/raw_data/회계 감리 지적 기업.csv')

In [26]:
print('fraud 로우 수: ', fraud.shape)
print('fraud 기업 수: ', fraud.drop_duplicates('거래소코드').shape)

fraud 로우 수:  (426, 5)
fraud 기업 수:  (138, 5)

In [27]:
# 중복 행 제거 후 인덱스 리셋
fraud = fraud.drop_duplicates().reset_index(drop=True)

In [28]:
print('fraud 로우 수: ', fraud.shape)
print('fraud 기업 수: ', fraud.drop_duplicates('거래소코드').shape)

fraud 로우 수:  (426, 5)
fraud 기업 수:  (138, 5)

In [54]:
fraud1 = fraud.drop_duplicates()

In [56]:
len(fraud1[fraud1['기업유형']== '코스피'])

149

In [50]:
len(fraud[fraud['기업유형']== '코스닥'])

277

In [51]:
149+277

426

In [47]:
fraud.columns

Index(['기업명', '거래소코드', '기업유형', '회계년도', '이익 과대계상 (비용 과소계상)'], dtype='object')

### 기준이 되는 데이터 타입 맞추기

In [29]:
listed[['거래소코드', '회계년도']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 23293 entries, 0 to 27694
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   거래소코드   23293 non-null  int64
 1   회계년도    23293 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1)
memory usage: 545.9 KB

In [30]:
fraud[['거래소코드', '회계년도']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426 entries, 0 to 425
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   거래소코드   426 non-null    int64
 1   회계년도    426 non-null    int64
dtypes: int64(2)
memory usage: 6.8 KB

In [31]:
listed['회계년도'] = listed['회계년도'].dt.year

### pd.merge(listed, fraud, on=['거래소코드', '회계년도'])

In [32]:
listed = pd.merge(listed, fraud, on=['거래소코드', '회계년도'])

In [33]:
listed.shape

(389, 196)

In [34]:
listed.drop_duplicates('거래소코드').shape

(132, 196)

In [35]:
print(listed[listed['기업유형'] == '코스피'].shape)
print(listed[listed['기업유형'] == '코스닥'].shape)

(128, 196)
(261, 196)

In [36]:
print(listed[listed['기업유형'] == '코스피'].drop_duplicates('거래소코드').shape)
print(listed[listed['기업유형'] == '코스닥'].drop_duplicates('거래소코드').shape)

(40, 196)
(92, 196)

# 정리

In [37]:
listed.columns

Index(['회사명', '거래소코드', '회계년도', '소속코드', '통계청 한국표준산업분류 코드 10차(대분류)', '산업코드',
       '산업명', '상장일', '상장폐지일', '현금및현금성자산(*)(IFRS연결)(천원)',
       ...
       '지분법적용투자주식손상차손(IFRS연결)(천원)', '기부금(IFRS연결)(천원)', '투자자산처분손실(IFRS연결)(천원)',
       '보상비(IFRS연결)(천원)', '법인세추납액(IFRS연결)(천원)', '전기오류수정손실(IFRS연결)(천원)',
       '법인세비용(IFRS연결)(천원)', '기업명', '기업유형', '이익 과대계상 (비용 과소계상)'],
      dtype='object', length=196)

In [38]:
listed = listed.drop(columns = ['기업명', '기업유형'])
listed.columns

Index(['회사명', '거래소코드', '회계년도', '소속코드', '통계청 한국표준산업분류 코드 10차(대분류)', '산업코드',
       '산업명', '상장일', '상장폐지일', '현금및현금성자산(*)(IFRS연결)(천원)',
       ...
       '외환차손(IFRS연결)(천원).1', '외화환산손실(IFRS연결)(천원).1',
       '지분법적용투자주식손상차손(IFRS연결)(천원)', '기부금(IFRS연결)(천원)', '투자자산처분손실(IFRS연결)(천원)',
       '보상비(IFRS연결)(천원)', '법인세추납액(IFRS연결)(천원)', '전기오류수정손실(IFRS연결)(천원)',
       '법인세비용(IFRS연결)(천원)', '이익 과대계상 (비용 과소계상)'],
      dtype='object', length=194)

In [39]:
listed = listed.rename(columns={'회사명_x': '회사명', '이익 과대계상 (비용 과소계상)': 'label'})
listed.columns

Index(['회사명', '거래소코드', '회계년도', '소속코드', '통계청 한국표준산업분류 코드 10차(대분류)', '산업코드',
       '산업명', '상장일', '상장폐지일', '현금및현금성자산(*)(IFRS연결)(천원)',
       ...
       '외환차손(IFRS연결)(천원).1', '외화환산손실(IFRS연결)(천원).1',
       '지분법적용투자주식손상차손(IFRS연결)(천원)', '기부금(IFRS연결)(천원)', '투자자산처분손실(IFRS연결)(천원)',
       '보상비(IFRS연결)(천원)', '법인세추납액(IFRS연결)(천원)', '전기오류수정손실(IFRS연결)(천원)',
       '법인세비용(IFRS연결)(천원)', 'label'],
      dtype='object', length=194)

In [40]:
listed_describe = listed.iloc[:, 8:-1].describe()
listed_describe

,현금및현금성자산(*)(IFRS연결)(천원),유동금융자산(*)(IFRS연결)(천원),매출채권 및 기타유동채권(*)(IFRS연결)(천원),이연법인세자산(IFRS연결)(천원),상각후원가측정 유가증권(IFRS연결)(천원),매출채권(IFRS연결)(천원),미수금(IFRS연결)(천원),단기대여금(IFRS연결)(천원),선급금(IFRS연결)(천원),기타유동자산(IFRS연결)(천원),...,재고자산감모손실(IFRS연결)(천원),외환차손(IFRS연결)(천원).1,외화환산손실(IFRS연결)(천원).1,지분법적용투자주식손상차손(IFRS연결)(천원),기부금(IFRS연결)(천원),투자자산처분손실(IFRS연결)(천원),보상비(IFRS연결)(천원),법인세추납액(IFRS연결)(천원),전기오류수정손실(IFRS연결)(천원),법인세비용(IFRS연결)(천원)
count,3.000000e+02,3.000000e+02,3.000000e+02,3.000000e+02,1.010000e+02,3.000000e+02,3.000000e+02,3.000000e+02,3.000000e+02,3.000000e+02,...,300.0,3.000000e+02,3.000000e+02,300.0,300.0,300.0,300.000000,300.0,300.0,3.000000e+02
mean,1.023169e+08,7.235860e+07,3.625073e+08,2.658337e+07,2.396934e+05,1.437684e+08,3.886547e+07,1.588461e+07,4.786720e+07,1.378927e+07,...,0.0,8.048355e+06,5.230259e+06,0.0,0.0,0.0,11264.490000,0.0,0.0,1.140763e+07
std,3.281002e+08,2.438264e+08,1.156712e+09,1.105552e+08,2.042324e+06,4.582975e+08,1.413641e+08,5.979140e+07,1.742567e+08,1.293782e+08,...,0.0,5.357237e+07,2.746298e+07,0.0,0.0,0.0,72862.132651,0.0,0.0,8.511855e+07
min,8.790000e+02,0.000000e+00,6.185640e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,-9.506336e+08
25%,2.938054e+06,1.541251e+06,1.015172e+07,0.000000e+00,0.000000e+00,7.815650e+06,3.924672e+05,2.450000e+04,4.224030e+05,0.000000e+00,...,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000e+00
50%,1.142865e+07,6.121410e+06,2.471884e+07,6.810865e+05,0.000000e+00,2.008883e+07,1.936490e+06,8.716900e+05,1.931872e+06,0.000000e+00,...,0.0,4.099450e+04,2.550500e+03,0.0,0.0,0.0,0.000000,0.0,0.0,3.360655e+05
75%,4.095851e+07,2.395476e+07,1.048516e+08,6.086311e+06,0.000000e+00,6.468767e+07,8.583851e+06,6.163766e+06,7.966051e+06,0.000000e+00,...,0.0,8.241258e+05,3.726665e+05,0.0,0.0,0.0,0.000000,0.0,0.0,4.523054e+06
max,2.542381e+09,2.099634e+09,7.980449e+09,1.335461e+09,2.029100e+07,3.595024e+09,1.095078e+09,7.598982e+08,1.743728e+09,1.752561e+09,...,0.0,7.328480e+08,3.391720e+08,0.0,0.0,0.0,745141.000000,0.0,0.0,4.191244e+08

### 중복된 내용 drop
- 회계 감리 지적 기업을 정리하는 과정에서 팀원 간 겹치는 보고서가 있었음.

In [41]:
listed[listed['회사명'] == '(주)제이테크놀로지']

,회사명,거래소코드,회계년도,소속코드,통계청 한국표준산업분류 코드 10차(대분류),산업코드,산업명,상장일,상장폐지일,현금및현금성자산(*)(IFRS연결)(천원),...,외환차손(IFRS연결)(천원).1,외화환산손실(IFRS연결)(천원).1,지분법적용투자주식손상차손(IFRS연결)(천원),기부금(IFRS연결)(천원),투자자산처분손실(IFRS연결)(천원),보상비(IFRS연결)(천원),법인세추납액(IFRS연결)(천원),전기오류수정손실(IFRS연결)(천원),법인세비용(IFRS연결)(천원),label
271,(주)제이테크놀로지,35480,2012,4,91,32605,스포츠 및 오락관련 서비스업,1999-11-18,2019/12/12,2566470.0,...,976938.0,470927.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
272,(주)제이테크놀로지,35480,2013,4,91,32605,스포츠 및 오락관련 서비스업,1999-11-18,2019/12/12,5670234.0,...,515384.0,198206.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
273,(주)제이테크놀로지,35480,2014,4,91,32605,스포츠 및 오락관련 서비스업,1999-11-18,2019/12/12,15842807.0,...,333368.0,14845.0,0.0,0.0,0.0,0.0,0.0,0.0,106521.0,1
274,(주)제이테크놀로지,35480,2015,4,91,189102,스포츠 및 오락관련 서비스업,1999-11-18,2019/12/12,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
275,(주)제이테크놀로지,35480,2016,4,91,189102,스포츠 및 오락관련 서비스업,1999-11-18,2019/12/12,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
276,(주)제이테크놀로지,35480,2017,4,91,189102,스포츠 및 오락관련 서비스업,1999-11-18,2019/12/12,306672.0,...,133431.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-319128.0,1

In [42]:
listed = listed.drop_duplicates()
listed

,회사명,거래소코드,회계년도,소속코드,통계청 한국표준산업분류 코드 10차(대분류),산업코드,산업명,상장일,상장폐지일,현금및현금성자산(*)(IFRS연결)(천원),...,외환차손(IFRS연결)(천원).1,외화환산손실(IFRS연결)(천원).1,지분법적용투자주식손상차손(IFRS연결)(천원),기부금(IFRS연결)(천원),투자자산처분손실(IFRS연결)(천원),보상비(IFRS연결)(천원),법인세추납액(IFRS연결)(천원),전기오류수정손실(IFRS연결)(천원),법인세비용(IFRS연결)(천원),label
0,(주)다이나믹디자인,145210,2015,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,10376890.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,184992.0,1
1,(주)다이나믹디자인,145210,2016,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,15192647.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7248212.0,1
2,(주)다이나믹디자인,145210,2017,1,29,32902,기타 기계 및 장비 제조업,2015-03-19,NaN,6564156.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-696299.0,1
3,(주)대우건설,47040,2012,1,41,64101,종합 건설업,2001-03-23,NaN,388440274.0,...,38000000.0,23052000.0,0.0,0.0,0.0,0.0,0.0,0.0,54918791.0,0
4,(주)대우건설,47040,2013,1,41,64101,종합 건설업,2001-03-23,NaN,409596263.0,...,34514000.0,23702000.0,0.0,0.0,0.0,0.0,0.0,0.0,-121688653.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,한솔아이원스(주),114810,2017,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
385,한솔아이원스(주),114810,2018,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
386,한솔아이원스(주),114810,2019,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,12310161.0,...,821838.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2093131.0,1
387,한솔아이원스(주),114810,2020,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,9274990.0,...,799836.0,2359896.0,0.0,0.0,0.0,0.0,0.0,0.0,2536049.0,1
388,한솔아이원스(주),114810,2021,5,29,32902,기타 기계 및 장비 제조업,2013-02-07,NaN,16490063.0,...,375920.0,152568.0,0.0,0.0,0.0,0.0,0.0,0.0,10788434.0,1

In [43]:
listed_describe = listed.iloc[:, 8:-1].describe()
listed_describe

,현금및현금성자산(*)(IFRS연결)(천원),유동금융자산(*)(IFRS연결)(천원),매출채권 및 기타유동채권(*)(IFRS연결)(천원),이연법인세자산(IFRS연결)(천원),상각후원가측정 유가증권(IFRS연결)(천원),매출채권(IFRS연결)(천원),미수금(IFRS연결)(천원),단기대여금(IFRS연결)(천원),선급금(IFRS연결)(천원),기타유동자산(IFRS연결)(천원),...,재고자산감모손실(IFRS연결)(천원),외환차손(IFRS연결)(천원).1,외화환산손실(IFRS연결)(천원).1,지분법적용투자주식손상차손(IFRS연결)(천원),기부금(IFRS연결)(천원),투자자산처분손실(IFRS연결)(천원),보상비(IFRS연결)(천원),법인세추납액(IFRS연결)(천원),전기오류수정손실(IFRS연결)(천원),법인세비용(IFRS연결)(천원)
count,3.000000e+02,3.000000e+02,3.000000e+02,3.000000e+02,1.010000e+02,3.000000e+02,3.000000e+02,3.000000e+02,3.000000e+02,3.000000e+02,...,300.0,3.000000e+02,3.000000e+02,300.0,300.0,300.0,300.000000,300.0,300.0,3.000000e+02
mean,1.023169e+08,7.235860e+07,3.625073e+08,2.658337e+07,2.396934e+05,1.437684e+08,3.886547e+07,1.588461e+07,4.786720e+07,1.378927e+07,...,0.0,8.048355e+06,5.230259e+06,0.0,0.0,0.0,11264.490000,0.0,0.0,1.140763e+07
std,3.281002e+08,2.438264e+08,1.156712e+09,1.105552e+08,2.042324e+06,4.582975e+08,1.413641e+08,5.979140e+07,1.742567e+08,1.293782e+08,...,0.0,5.357237e+07,2.746298e+07,0.0,0.0,0.0,72862.132651,0.0,0.0,8.511855e+07
min,8.790000e+02,0.000000e+00,6.185640e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,-9.506336e+08
25%,2.938054e+06,1.541251e+06,1.015172e+07,0.000000e+00,0.000000e+00,7.815650e+06,3.924672e+05,2.450000e+04,4.224030e+05,0.000000e+00,...,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000e+00
50%,1.142865e+07,6.121410e+06,2.471884e+07,6.810865e+05,0.000000e+00,2.008883e+07,1.936490e+06,8.716900e+05,1.931872e+06,0.000000e+00,...,0.0,4.099450e+04,2.550500e+03,0.0,0.0,0.0,0.000000,0.0,0.0,3.360655e+05
75%,4.095851e+07,2.395476e+07,1.048516e+08,6.086311e+06,0.000000e+00,6.468767e+07,8.583851e+06,6.163766e+06,7.966051e+06,0.000000e+00,...,0.0,8.241258e+05,3.726665e+05,0.0,0.0,0.0,0.000000,0.0,0.0,4.523054e+06
max,2.542381e+09,2.099634e+09,7.980449e+09,1.335461e+09,2.029100e+07,3.595024e+09,1.095078e+09,7.598982e+08,1.743728e+09,1.752561e+09,...,0.0,7.328480e+08,3.391720e+08,0.0,0.0,0.0,745141.000000,0.0,0.0,4.191244e+08

# csv로 저장

In [45]:
# listed.to_csv('../data/processed_data/재무지표.csv', index=False, encoding='UTF-8-sig')

In [46]:
# listed_describe.to_csv('../data/processed_data/재무지표_기초통계량.csv', index=False, encoding='UTF-8-sig')